"Filed out from Dolphin Smalltalk"!

Object subclass: #MySQLTypes
	instanceVariableNames: ''
	classVariableNames: 'TypeBIT TypeBLOB TypeDATE TypeDATETIME TypeDECIMAL TypeDOUBLE TypeENUM TypeFLOAT TypeGEOMETRY TypeINT24 TypeJSON TypeLONG TypeLONGBLOB TypeLONGLONG TypeMEDIUMBLOB TypeNEWDATE TypeNEWDECIMAL TypeNULL TypeSET TypeSHORT TypeSTRING TypeTIME TypeTIMESTAMP TypeTINY TypeTINYBLOB TypeVARCHAR TypeVARSTRING TypeYEAR'
	poolDictionaries: ''
	classInstanceVariableNames: ''!

MySQLTypes guid: (GUID fromString: '{8b754205-daf8-48e4-aef1-6dc5b8b4f684}')!

MySQLTypes comment: 'MySQLTypes class	instanceVariableNames: ''blobTypes dateTimeTypes integerTypes stringTypes realTypes'''!

!MySQLTypes categoriesForClass!Unclassified! !

!MySQLTypes class methodsFor!

initFieldTypes 	TypeBIT := 16. 	TypeBLOB := 252. 	TypeDATE := 10. 	TypeDATETIME := 12. 	TypeDECIMAL := 0. 	TypeDOUBLE := 5. 	TypeENUM := 247. 	TypeFLOAT := 4. 	TypeGEOMETRY := 255. 	TypeINT24 := 9.	TypeJSON := 245. 	TypeLONG := 3. 	TypeLONGLONG := 8. 	TypeLONGBLOB := 251. 	TypeMEDIUMBLOB := 250. 	TypeNEWDATE := 14. 	TypeNEWDECIMAL := 246. 	TypeNULL := 6. 	TypeSET := 248. 	TypeSHORT := 2. 	TypeSTRING := 254. 	TypeTIME := 11. 	TypeTIMESTAMP := 7. 	TypeTINY := 1. 	TypeTINYBLOB := 249. 	TypeVARCHAR := 15. 	TypeVARSTRING := 253. 	TypeYEAR := 13.!

initialize	"MySQLTypes initialize"	self initFieldTypes! !

!MySQLTypes class categoriesForMethods!
initFieldTypes!private / initialization!public! !
initialize!class initialization!public! !
!

