"Filed out from Dolphin Smalltalk"!

MySQLDriverError subclass: #MySQLBindError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

MySQLBindError guid: (GUID fromString: '{cfdd0349-2262-4253-8705-77230bf5d9ed}')!

MySQLBindError comment: 'MySQLDriverError subclass: #MySQLInvalidPacketError	instanceVariableNames: ''''	classVariableNames: ''''	package: ''MySQL-Core-Exception'''!

!MySQLBindError categoriesForClass!MySQL-Core-Exception! !

