"Filed out from Dolphin Smalltalk"!

MySQLDriverError subclass: #MySQLUnsuportedAuthError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

MySQLUnsuportedAuthError guid: (GUID fromString: '{264ed3aa-b952-4485-90a1-6fdd81bc0ea6}')!

MySQLUnsuportedAuthError comment: 'MySQLDriverError subclass: #MySQLUnsupportedProtocolError	instanceVariableNames: ''''	classVariableNames: ''''	package: ''MySQL-Core-Exception'''!

!MySQLUnsuportedAuthError categoriesForClass!MySQL-Core-Exception! !

