"Filed out from Dolphin Smalltalk"!

MySQLDriverError subclass: #MySQLInvalidPacketError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

MySQLInvalidPacketError guid: (GUID fromString: '{dc65ca12-1210-41ae-b951-50ed4ca04de3}')!

MySQLInvalidPacketError comment: 'MySQLDriverError subclass: #MySQLInvalidRowAccess	instanceVariableNames: ''''	classVariableNames: ''''	package: ''MySQL-Core-Exception'''!

!MySQLInvalidPacketError categoriesForClass!MySQL-Core-Exception! !

