"Filed out from Dolphin Smalltalk"!

MySQLDriverError subclass: #MySQLNameLookupFailure
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

MySQLNameLookupFailure guid: (GUID fromString: '{175c90aa-81c8-42ef-8b76-45fae33bab9e}')!

MySQLNameLookupFailure comment: 'MySQLDriverError subclass: #MySQLNoConnectionError	instanceVariableNames: ''''	classVariableNames: ''''	package: ''MySQL-Core-Exception'''!

!MySQLNameLookupFailure categoriesForClass!MySQL-Core-Exception! !

