"Filed out from Dolphin Smalltalk"!

MySQLCommandWithStatement subclass: #MySQLCommandFetch
	instanceVariableNames: 'numRows resultSetContext'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

MySQLCommandFetch guid: (GUID fromString: '{c1e3a8c8-58f1-4ed6-9c5f-fbabff760ac3}')!

MySQLCommandFetch comment: 'MySQL fetch command'!

!MySQLCommandFetch categoriesForClass!MySQL-Core-Command! !

!MySQLCommandFetch methodsFor!

commandArg	^ByteArray		streamContents: [ :strm | 			strm				nextPut: (stmtId byteAt: 1);				nextPut: (stmtId byteAt: 2);				nextPut: (stmtId byteAt: 3);				nextPut: (stmtId byteAt: 4);				nextPut: (numRows byteAt: 1);				nextPut: (numRows byteAt: 2);				nextPut: (numRows byteAt: 3);				nextPut: (numRows byteAt: 4) ]!

commandCode	^ ComStmtFetch 	!

numRows: count	numRows := count	!

readResponse	| resp |	resp := self readResult.	^ resp	!

readResult	| pkt fieldsEof rows fields rowsEof |	pkt := MySQLPacket from: session peek.	pkt isError ifTrue: [^ MySQLError from: session read].		"If not error then zero or more row data packets followed by eof packet"	fields := resultSetContext fields.	fieldsEof := resultSetContext fieldsEof.	fieldsEof hasOpenCursor ifTrue: [			rows := self readRowData: fields.		rowsEof := self readEof. "eof"].		^ resultSetContext		rows: rows asOrderedCollection;		rowsEof: rowsEof;		yourself		!

resultSetContext: partialResultSet	resultSetContext := partialResultSet 	! !

!MySQLCommandFetch categoriesForMethods!
commandArg!defaults!public! !
commandCode!defaults!public! !
numRows:!accessing!public! !
readResponse!public!reading! !
readResult!public!reading! !
resultSetContext:!accessing!public! !
!

