"Filed out from Dolphin Smalltalk"!

MySQLDriverError subclass: #MySQLNoConnectionError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

MySQLNoConnectionError guid: (GUID fromString: '{e780df32-fec8-4d1e-8157-2e0f0ad660bc}')!

MySQLNoConnectionError comment: 'MySQLDriverError subclass: #MySQLUnsuportedAuthError	instanceVariableNames: ''''	classVariableNames: ''''	package: ''MySQL-Core-Exception'''!

!MySQLNoConnectionError categoriesForClass!MySQL-Core-Exception! !

