"Filed out from Dolphin Smalltalk"!

MySQLDriverError subclass: #MySQLStatementError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

MySQLStatementError guid: (GUID fromString: '{acdad442-ec8b-45d2-b28d-c712672ad2c4}')!

MySQLStatementError comment: ''!

!MySQLStatementError categoriesForClass!MySQL-Core-Exception! !

!MySQLStatementError methodsFor!

statement
	^tag! !

!MySQLStatementError categoriesForMethods!
statement!accessing!public! !
!

