"Filed out from Dolphin Smalltalk"!

MySQLResult subclass: #MySQLComplexResult
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

MySQLComplexResult guid: (GUID fromString: '{529538c8-98c1-449b-aaf4-f0c33b5bba3e}')!

MySQLComplexResult comment: 'MySQLComplexResult class	instanceVariableNames: '''''!

!MySQLComplexResult categoriesForClass!MySQL-Core-Packet-Results! !

