"Filed out from Dolphin Smalltalk"!

MySQLDriverError subclass: #MySQLInvalidRowAccess
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

MySQLInvalidRowAccess guid: (GUID fromString: '{4524c761-e9bb-4513-b04d-cdb4aa84d0f3}')!

MySQLInvalidRowAccess comment: 'MySQLDriverError subclass: #MySQLNameLookupFailure	instanceVariableNames: ''''	classVariableNames: ''''	package: ''MySQL-Core-Exception'''!

!MySQLInvalidRowAccess categoriesForClass!MySQL-Core-Exception! !

