"Filed out from Dolphin Smalltalk"!

MySQLDriverError subclass: #MySQLUnsupportedProtocolError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

MySQLUnsupportedProtocolError guid: (GUID fromString: '{e6272b4f-ddc3-456b-8359-41b5db8dca96}')!

MySQLUnsupportedProtocolError comment: 'MySQLPacket subclass: #MySQLResult	instanceVariableNames: ''nextResult''	classVariableNames: ''''	package: ''MySQL-Core-Packet-Results'''!

!MySQLUnsupportedProtocolError categoriesForClass!MySQL-Core-Exception! !

